x=int(input("Podaj x: "))
y=int(input("Podaj y: "))
if x==0 and y==0: print("plane is located in (0,0)")
if(x==0 and (y>0 or y<0)): print("plane is located on x axis")
if((x>0 or x<0) and y==0): print ("plane is located on y axis")
if x>0 and y>0: print ("plane is in first quadrant")
if x<0 and y>0: print ("plane is in second quadrant")
if x<0 and y<0: print ("plane is in third quadrant")
if x>0 and y<0: print ("plane is in fourth quadrant")